2025-07-02 08:07:47,619 | INFO | Выгрузка остатков на складах на дату 2024-06-30T23:59:59 по подразделению fa85468e-af74-495e-a33c-37d6562e4699
2025-07-02 08:07:48,196 | INFO | HTTP Request: POST https://pizzayolo.iiko.it/resto/api/auth "HTTP/1.1 200 OK"
2025-07-02 08:07:48,196 | INFO | Запрос к iiko: https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores
2025-07-02 08:07:48,197 | INFO | Параметры: {'key': '8fdad717-7599-c71f-db19-3f0e0ded8b4c', 'timestamp': '2024-06-30T23:59:59', 'department': 'fa85468e-af74-495e-a33c-37d6562e4699'}
2025-07-02 08:07:48,745 | INFO | HTTP Request: GET https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores?key=8fdad717-7599-c71f-db19-3f0e0ded8b4c&timestamp=2024-06-30T23%3A59%3A59&department=fa85468e-af74-495e-a33c-37d6562e4699 "HTTP/1.1 200 OK"
2025-07-02 08:07:48,787 | INFO | Status code: 200
2025-07-02 08:07:48,788 | INFO | Получено строк: 379
2025-07-02 08:07:49,141 | INFO | Сохранено в store_balance.xlsx
2025-07-02 08:08:21,644 | INFO | Выгрузка остатков на складах на дату 2024-06-30T23:59:59 по подразделению fa85468e-af74-495e-a33c-37d6562e4699
2025-07-02 08:08:23,247 | INFO | HTTP Request: POST https://pizzayolo.iiko.it/resto/api/auth "HTTP/1.1 200 OK"
2025-07-02 08:08:23,249 | INFO | Запрос к iiko: https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores
2025-07-02 08:08:23,249 | INFO | Параметры: {'key': '7f8dfe16-3156-b3e3-1930-3bf200497451', 'timestamp': '2024-06-30T23:59:59', 'department': 'fa85468e-af74-495e-a33c-37d6562e4699'}
2025-07-02 08:08:23,791 | INFO | HTTP Request: GET https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores?key=7f8dfe16-3156-b3e3-1930-3bf200497451&timestamp=2024-06-30T23%3A59%3A59&department=fa85468e-af74-495e-a33c-37d6562e4699 "HTTP/1.1 200 OK"
2025-07-02 08:08:23,793 | INFO | Status code: 200
2025-07-02 08:08:23,794 | INFO | Сырой ответ (первые 1000 символов):
2025-07-02 08:08:23,794 | INFO | [{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"db074634-c423-4924-b59d-4649743fff98","amount":1.73,"sum":1738.65},{"store":"742a458d-0046-417c-b19b-8164ba9f5be1","product":"06df1e7d-ae2a-430b-927d-e07be16f41d7","amount":1,"sum":4320},{"store":"722b4cd4-2be7-4b10-9c3f-d0507ff11d2d","product":"40762358-414a-4dbe-9b22-01134e87ac33","amount":0.000491,"sum":0.56},{"store":"b13628a2-8874-4420-9b26-9366afa5e9c0","product":"4ac392ce-aa8f-46e5-8339-f093d999abe5","amount":13,"sum":4672},{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"2e9b1471-d399-4bb8-8b83-fcfa60250771","amount":3.4,"sum":0},{"store":"b260ae8a-0144-41d7-a5ba-44ea975b1986","product":"968d6a23-4671-43b5-8c3a-316d4956c483","amount":5,"sum":405},{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"76dfe77b-fa04-4ff4-8ab5-c7ef10819e89","amount":0.22,"sum":1716},{"store":"722b4cd4-2be7-4b10-9c3f-d0507ff11d2d","product":"96445e23-47a5-4ae9-81e4-40a7125de7ff","amount":0.13,"sum":84.37},{"store":"722b4cd4-2
2025-07-02 08:14:21,621 | INFO | Выгрузка остатков на складах на дату 2024-06-30T23:59:59 по подразделению fa85468e-af74-495e-a33c-37d6562e4699
2025-07-02 08:14:22,203 | INFO | HTTP Request: POST https://pizzayolo.iiko.it/resto/api/auth "HTTP/1.1 200 OK"
2025-07-02 08:14:22,205 | INFO | Запрос к iiko: https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores
2025-07-02 08:14:22,205 | INFO | Параметры: {'key': 'de104208-467a-826c-3837-68c15deb94c9', 'timestamp': '2024-06-30T23:59:59', 'department': 'fa85468e-af74-495e-a33c-37d6562e4699'}
2025-07-02 08:14:22,716 | INFO | HTTP Request: GET https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores?key=de104208-467a-826c-3837-68c15deb94c9&timestamp=2024-06-30T23%3A59%3A59&department=fa85468e-af74-495e-a33c-37d6562e4699 "HTTP/1.1 200 OK"
2025-07-02 08:14:22,769 | INFO | Status code: 200
2025-07-02 08:14:22,770 | INFO | Сырой ответ (первые 1000 символов): [{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"db074634-c423-4924-b59d-4649743fff98","amount":1.73,"sum":1738.65},{"store":"742a458d-0046-417c-b19b-8164ba9f5be1","product":"06df1e7d-ae2a-430b-927d-e07be16f41d7","amount":1,"sum":4320},{"store":"722b4cd4-2be7-4b10-9c3f-d0507ff11d2d","product":"40762358-414a-4dbe-9b22-01134e87ac33","amount":0.000491,"sum":0.56},{"store":"b13628a2-8874-4420-9b26-9366afa5e9c0","product":"4ac392ce-aa8f-46e5-8339-f093d999abe5","amount":13,"sum":4672},{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"2e9b1471-d399-4bb8-8b83-fcfa60250771","amount":3.4,"sum":0},{"store":"b260ae8a-0144-41d7-a5ba-44ea975b1986","product":"968d6a23-4671-43b5-8c3a-316d4956c483","amount":5,"sum":405},{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"76dfe77b-fa04-4ff4-8ab5-c7ef10819e89","amount":0.22,"sum":1716},{"store":"722b4cd4-2be7-4b10-9c3f-d0507ff11d2d","product":"96445e23-47a5-4ae9-81e4-40a7125de7ff","amount":0.13,"sum":84.37},{"store":"722b4cd4-2
2025-07-02 08:14:29,899 | INFO | Показано 10 строк из 379 остатков
2025-07-02 08:14:29,922 | ERROR | Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001AB218C7100>
transport: <_SelectorSocketTransport closing fd=908>
Traceback (most recent call last):
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [WinError 10038] Сделана попытка выполнить операцию на объекте, не являющемся сокетом

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 930, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 725, in _fatal_error
    self._force_close(exc)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 737, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 753, in call_soon
    self._check_closed()
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-07-02 08:15:41,168 | INFO | Выгрузка остатков на складах на дату 2024-06-30T23:59:59 по подразделению fa85468e-af74-495e-a33c-37d6562e4699
2025-07-02 08:15:41,787 | INFO | HTTP Request: POST https://pizzayolo.iiko.it/resto/api/auth "HTTP/1.1 200 OK"
2025-07-02 08:15:41,787 | INFO | Запрос к iiko: https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores
2025-07-02 08:15:41,789 | INFO | Параметры: {'key': '40d9c74c-87fd-dfe6-167b-27039ed46558', 'timestamp': '2024-06-30T23:59:59', 'department': 'fa85468e-af74-495e-a33c-37d6562e4699'}
2025-07-02 08:15:42,260 | INFO | HTTP Request: GET https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores?key=40d9c74c-87fd-dfe6-167b-27039ed46558&timestamp=2024-06-30T23%3A59%3A59&department=fa85468e-af74-495e-a33c-37d6562e4699 "HTTP/1.1 200 OK"
2025-07-02 08:15:42,319 | INFO | Status code: 200
2025-07-02 08:15:42,320 | INFO | Сырой ответ (первые 1000 символов): [{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"db074634-c423-4924-b59d-4649743fff98","amount":1.73,"sum":1738.65},{"store":"742a458d-0046-417c-b19b-8164ba9f5be1","product":"06df1e7d-ae2a-430b-927d-e07be16f41d7","amount":1,"sum":4320},{"store":"722b4cd4-2be7-4b10-9c3f-d0507ff11d2d","product":"40762358-414a-4dbe-9b22-01134e87ac33","amount":0.000491,"sum":0.56},{"store":"b13628a2-8874-4420-9b26-9366afa5e9c0","product":"4ac392ce-aa8f-46e5-8339-f093d999abe5","amount":13,"sum":4672},{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"2e9b1471-d399-4bb8-8b83-fcfa60250771","amount":3.4,"sum":0},{"store":"b260ae8a-0144-41d7-a5ba-44ea975b1986","product":"968d6a23-4671-43b5-8c3a-316d4956c483","amount":5,"sum":405},{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"76dfe77b-fa04-4ff4-8ab5-c7ef10819e89","amount":0.22,"sum":1716},{"store":"722b4cd4-2be7-4b10-9c3f-d0507ff11d2d","product":"96445e23-47a5-4ae9-81e4-40a7125de7ff","amount":0.13,"sum":84.37},{"store":"722b4cd4-2
2025-07-02 08:15:50,826 | INFO | Показано 10 строк из 379 остатков
2025-07-02 08:15:50,849 | ERROR | Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x00000135FF15FEE0>
transport: <_SelectorSocketTransport closing fd=408>
Traceback (most recent call last):
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [WinError 10038] Сделана попытка выполнить операцию на объекте, не являющемся сокетом

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 930, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 725, in _fatal_error
    self._force_close(exc)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 737, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 753, in call_soon
    self._check_closed()
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-07-02 08:17:15,407 | INFO | Выгрузка остатков на складах на дату 2024-06-30T23:59:59 по подразделению fa85468e-af74-495e-a33c-37d6562e4699
2025-07-02 08:17:15,985 | INFO | HTTP Request: POST https://pizzayolo.iiko.it/resto/api/auth "HTTP/1.1 200 OK"
2025-07-02 08:17:15,986 | INFO | Запрос к iiko: https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores
2025-07-02 08:17:15,986 | INFO | Параметры: {'key': '78e3b40a-ca47-96a7-83f0-60477494ad15', 'timestamp': '2024-06-30T23:59:59', 'department': 'fa85468e-af74-495e-a33c-37d6562e4699'}
2025-07-02 08:17:16,562 | INFO | HTTP Request: GET https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores?key=78e3b40a-ca47-96a7-83f0-60477494ad15&timestamp=2024-06-30T23%3A59%3A59&department=fa85468e-af74-495e-a33c-37d6562e4699 "HTTP/1.1 200 OK"
2025-07-02 08:17:16,621 | INFO | Status code: 200
2025-07-02 08:17:16,621 | INFO | Сырой ответ (первые 1000 символов): [{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"db074634-c423-4924-b59d-4649743fff98","amount":1.73,"sum":1738.65},{"store":"742a458d-0046-417c-b19b-8164ba9f5be1","product":"06df1e7d-ae2a-430b-927d-e07be16f41d7","amount":1,"sum":4320},{"store":"722b4cd4-2be7-4b10-9c3f-d0507ff11d2d","product":"40762358-414a-4dbe-9b22-01134e87ac33","amount":0.000491,"sum":0.56},{"store":"b13628a2-8874-4420-9b26-9366afa5e9c0","product":"4ac392ce-aa8f-46e5-8339-f093d999abe5","amount":13,"sum":4672},{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"2e9b1471-d399-4bb8-8b83-fcfa60250771","amount":3.4,"sum":0},{"store":"b260ae8a-0144-41d7-a5ba-44ea975b1986","product":"968d6a23-4671-43b5-8c3a-316d4956c483","amount":5,"sum":405},{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"76dfe77b-fa04-4ff4-8ab5-c7ef10819e89","amount":0.22,"sum":1716},{"store":"722b4cd4-2be7-4b10-9c3f-d0507ff11d2d","product":"96445e23-47a5-4ae9-81e4-40a7125de7ff","amount":0.13,"sum":84.37},{"store":"722b4cd4-2
2025-07-02 08:17:24,660 | INFO | Показано 10 строк из 379 остатков
2025-07-02 08:17:24,684 | ERROR | Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000002186AB9FE80>
transport: <_SelectorSocketTransport closing fd=628>
Traceback (most recent call last):
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [WinError 10038] Сделана попытка выполнить операцию на объекте, не являющемся сокетом

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 930, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 725, in _fatal_error
    self._force_close(exc)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 737, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 753, in call_soon
    self._check_closed()
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-07-02 08:21:14,919 | INFO | Выгрузка остатков на складах на дату 2024-06-30T23:59:59 по подразделению fa85468e-af74-495e-a33c-37d6562e4699
2025-07-02 08:21:15,533 | INFO | HTTP Request: POST https://pizzayolo.iiko.it/resto/api/auth "HTTP/1.1 200 OK"
2025-07-02 08:21:15,534 | INFO | Запрос к iiko: https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores
2025-07-02 08:21:15,534 | INFO | Параметры: {'key': '0652464d-8048-352f-fe82-9bbeedd39304', 'timestamp': '2024-06-30T23:59:59', 'department': 'fa85468e-af74-495e-a33c-37d6562e4699'}
2025-07-02 08:21:16,040 | INFO | HTTP Request: GET https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores?key=0652464d-8048-352f-fe82-9bbeedd39304&timestamp=2024-06-30T23%3A59%3A59&department=fa85468e-af74-495e-a33c-37d6562e4699 "HTTP/1.1 200 OK"
2025-07-02 08:21:16,041 | INFO | Status code: 200
2025-07-02 08:21:16,041 | INFO | Сырой ответ (первые 1000 символов): [{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"db074634-c423-4924-b59d-4649743fff98","amount":1.73,"sum":1738.65},{"store":"742a458d-0046-417c-b19b-8164ba9f5be1","product":"06df1e7d-ae2a-430b-927d-e07be16f41d7","amount":1,"sum":4320},{"store":"722b4cd4-2be7-4b10-9c3f-d0507ff11d2d","product":"40762358-414a-4dbe-9b22-01134e87ac33","amount":0.000491,"sum":0.56},{"store":"b13628a2-8874-4420-9b26-9366afa5e9c0","product":"4ac392ce-aa8f-46e5-8339-f093d999abe5","amount":13,"sum":4672},{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"2e9b1471-d399-4bb8-8b83-fcfa60250771","amount":3.4,"sum":0},{"store":"b260ae8a-0144-41d7-a5ba-44ea975b1986","product":"968d6a23-4671-43b5-8c3a-316d4956c483","amount":5,"sum":405},{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"76dfe77b-fa04-4ff4-8ab5-c7ef10819e89","amount":0.22,"sum":1716},{"store":"722b4cd4-2be7-4b10-9c3f-d0507ff11d2d","product":"96445e23-47a5-4ae9-81e4-40a7125de7ff","amount":0.13,"sum":84.37},{"store":"722b4cd4-2
2025-07-02 08:21:23,585 | INFO | Показано 10 строк из 379 остатков
2025-07-02 08:21:23,607 | ERROR | Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x0000024096E1FFA0>
transport: <_SelectorSocketTransport closing fd=876>
Traceback (most recent call last):
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [WinError 10038] Сделана попытка выполнить операцию на объекте, не являющемся сокетом

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 930, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 725, in _fatal_error
    self._force_close(exc)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 737, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 753, in call_soon
    self._check_closed()
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2025-07-02 08:22:34,993 | INFO | Выгрузка остатков на складах на дату 2024-06-30T23:59:59 по подразделению fa85468e-af74-495e-a33c-37d6562e4699
2025-07-02 08:22:35,886 | INFO | HTTP Request: POST https://pizzayolo.iiko.it/resto/api/auth "HTTP/1.1 200 OK"
2025-07-02 08:22:35,887 | INFO | Запрос к iiko: https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores
2025-07-02 08:22:35,887 | INFO | Параметры: {'key': 'b1e2bac0-ca27-9734-7391-25b924ee56a2', 'timestamp': '2024-06-30T23:59:59', 'department': 'fa85468e-af74-495e-a33c-37d6562e4699'}
2025-07-02 08:22:36,453 | INFO | HTTP Request: GET https://pizzayolo.iiko.it/resto/api/v2/reports/balance/stores?key=b1e2bac0-ca27-9734-7391-25b924ee56a2&timestamp=2024-06-30T23%3A59%3A59&department=fa85468e-af74-495e-a33c-37d6562e4699 "HTTP/1.1 200 OK"
2025-07-02 08:22:36,454 | INFO | Status code: 200
2025-07-02 08:22:36,454 | INFO | Сырой ответ (первые 1000 символов): [{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"db074634-c423-4924-b59d-4649743fff98","amount":1.73,"sum":1738.65},{"store":"742a458d-0046-417c-b19b-8164ba9f5be1","product":"06df1e7d-ae2a-430b-927d-e07be16f41d7","amount":1,"sum":4320},{"store":"722b4cd4-2be7-4b10-9c3f-d0507ff11d2d","product":"40762358-414a-4dbe-9b22-01134e87ac33","amount":0.000491,"sum":0.56},{"store":"b13628a2-8874-4420-9b26-9366afa5e9c0","product":"4ac392ce-aa8f-46e5-8339-f093d999abe5","amount":13,"sum":4672},{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"2e9b1471-d399-4bb8-8b83-fcfa60250771","amount":3.4,"sum":0},{"store":"b260ae8a-0144-41d7-a5ba-44ea975b1986","product":"968d6a23-4671-43b5-8c3a-316d4956c483","amount":5,"sum":405},{"store":"44da7730-327d-4b01-94e5-5c63c8ff5798","product":"76dfe77b-fa04-4ff4-8ab5-c7ef10819e89","amount":0.22,"sum":1716},{"store":"722b4cd4-2be7-4b10-9c3f-d0507ff11d2d","product":"96445e23-47a5-4ae9-81e4-40a7125de7ff","amount":0.13,"sum":84.37},{"store":"722b4cd4-2
2025-07-02 08:22:44,279 | INFO | Показано 10 строк из 379 остатков
2025-07-02 08:22:44,301 | ERROR | Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001F9AA5481C0>
transport: <_SelectorSocketTransport closing fd=796>
Traceback (most recent call last):
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 924, in write
    n = self._sock.send(data)
OSError: [WinError 10038] Сделана попытка выполнить операцию на объекте, не являющемся сокетом

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 690, in _process_write_backlog
    self._transport.write(chunk)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 930, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 725, in _fatal_error
    self._force_close(exc)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\selector_events.py", line 737, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 753, in call_soon
    self._check_closed()
  File "C:\Users\egor0\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
